### ISSUE TITLE
Problem of multithreading.

### ISSUE THREAD

**Issue by a-velt** [lh3/bwa#102] opened 2017-01-04 14:15 UTC
Dear BWA developers,

First of all, I wish you an happy new year.

I am currently experiencing a problem with bwa-mem. In my lab, I have two nodes, one "old" node and a new node that we received four months ago, which has a "different" generation of processors (namely more recent processors). When I launch BWA on my "old" node, on one or more thread(s), I have no problem. When I launch BWA on 1 thread on my "new" node, I have no problem too. But when I launch BWA on multi-threads (e.g 5), the job runs without generating any results and never stops. I am obliged to stop him myself. For information, I run exactly the same command as on my old node. By setting the option -v to 2, I have no error/warning different between the jobs tested. On the new node, with multithreading, the job just keeps "turning in a vacuum".

Earlier I had already encountered this problem with the gsnap tool. The developer had advised me to use their latest version that solved this error.

But here, I use the last version of bwa : 
> bwa
Program: bwa (alignment via Burrows-Wheeler transformation)
Version: 0.7.15-r1142-dirty
Contact: Heng Li <lh3@sanger.ac.uk>
Usage:   bwa <command> [options]
Command: index         index sequences in the FASTA format
         mem           BWA-MEM algorithm
         fastmap       identify super-maximal exact matches
         pemerge       merge overlapping paired ends (EXPERIMENTAL)
         aln           gapped/ungapped alignment
         samse         generate alignment (single ended)
         sampe         generate alignment (paired ended)
         bwasw         BWA-SW for long queries
         shm           manage indices in shared memory
         fa2pac        convert FASTA to PAC format
         pac2bwt       generate BWT from PAC
         pac2bwtgen    alternative algorithm for generating BWT
         bwtupdate     update .bwt to the new format
         bwt2sa        generate SA from BWT and Occ
Note: To use BWA, you need to first index the genome with `bwa index'.
      There are three alignment algorithms in BWA: `mem', `bwasw', and
      `aln/samse/sampe'. If you are not sure which to use, try `bwa mem'
      first. Please `man ./bwa.1' for the manual.

So, have you ever heard of this problem of multithreading ? And do you have a solution?

Thank you very much.

Have a nice day,
Amandine

**Comment by lh3** [comment] 2017-01-04 14:24
Please see #91. What is your kernel version? It is interesting that gsnap is able to fix the issue.

**Comment by a-velt** [comment] 2017-01-04 14:39
Thank you for redirecting me.

My kernel version : 

> uname -r
2.6.32-504.el6.x86_64

**Comment by a-velt** [comment] 2017-01-12 12:54
Hi,

Are you working on a new BWA version correcting this error? Or maybe I can do something to correct this ?

Best,
Amandine

**Comment by lh3** [comment] 2017-01-12 12:56
I don't have the right CPU+kernel combination here to reproduce the issue. Without reproducing it at my hand, I am unable to fix the issue. Sorry.

**Comment by lh3** [comment] 2017-01-19 20:08
It just occurs to me that you can try to add option "-1" when you run bwa-mem. The full command line looks like:
```sh
bwa mem -1 ref.fa read1.fq.gz read2.fq.gz
```
Could you help to try this and see if it solves the problem? Thanks in advance!

**Comment by mbreese** [comment] 2017-02-10 14:00
I have this problem too (new hardware, old kernel).  CPU=E5-2680v4, Kernel=2.6.32-504.12.2.el6 (RHEL6.6). I'm not sure if this problem happens with newer versions of RHEL/CentOS or not. It might be a really rare issue.

I can can confirm that running `bwa mem -1` works (more accurately, avoids the deadlock). I'm happy to help test things if needed. We are currently stuck with bwa 0.7.12 for data harmonization reasons, but I'm happy to try patches. (I don't know where to start looking myself).

**Comment by dmckean** [comment] 2017-03-01 20:49
@mbreese If you can apply a patch, I think the proper one is described [here](https://groups.google.com/d/msg/mechanical-sympathy/QbmpZxp6C64/0M4_EbzSLj4J) (and [reported here](https://www.infoq.com/news/2015/05/redhat-futex)). Can't be sure as the update makes no mention of the issue.

**Comment by lh3** [comment] 2017-06-30 15:05
CC @dmckean, @mbreese, @a-velt, @timeu, @ebirn, @centredecalcul (see also #91)

This deadlock is caused by a bug in the Linux kernel which was [reported here][1] (particular thanks to @mbreese for pointing me to this thread and others). In brief, this bug appears to only affect [Haswell CPUs][2] but not older ones (not sure about more recent CPUs). It was introduced to kernel version 3.14 in Jan 2014 and [fixed][3] in version 3.18 in Oct 2014. Unfortunately, RHEL/CentOS backported this bug into RHEL 6.6, so the older kernel used in RHEL 6.6 also has the same bug. Red Hat has issued RHEL 6.6.z to fix the issue.

In summary, the deadlock is caused by a kernel bug. It is not a bwa bug. The ultimate solution is to apply a system patch as @dmckean said. Before applying the patch, you can use `bwa mem -1` to skip the part of code that may trigger the kernel bug. Adding this hidden option `-1` still enables multi-threading for mapping (as this part doesn't lock), but disables fastq reading and sam writing on different threads. This will marginally increase wall-clock time.

I will close this issue and #91. Thanks for all the reports.

[1]: https://groups.google.com/forum/#!msg/mechanical-sympathy/QbmpZxp6C64/BonaHiVbEmsJ
[2]: https://en.wikipedia.org/wiki/Haswell_(microarchitecture)
[3]: https://github.com/torvalds/linux/commit/76835b0ebf8a7fe85beb03c75121419a7dec52f0

**Closed by lh3** 2017-06-30 15:05 UTC
